---
title: "Interactive graph examples"
author: "Kazia Mermel"
date: "10/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here, we'll practice creating some interactive graphs and tables using built-in datasets in R packages.

 - Interactive plots: {plotly}
 - Interactive tables: {DT}
 
```{r, include = FALSE}
# attach packages
library(tidyverse)
library(plotly)
library(DT)
```
 
### A. Interactive graph of iris dimensions

Using Edgar Anderson's famous iris dataset, which is built into R so we don't have to read anything in

```{r, echo = FALSE}

iris_graph <- ggplot(data = iris, aes(x = Petal.Width, y = Petal.Length)) +
  geom_point(aes(size = Sepal.Width,
                 color = Species),
             alpha = 0.5) +
  theme_minimal() +
  labs(x = "Petal width (cm)",
       y = "Petal length (cm)",
       title = "My iris graph")

# iris_graph

# make it interactive
# always make sure static version works before you add interactivity, reactivity

ggplotly(iris_graph)
```

 